name: torch
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.2
  - pip=21.3
  - pytest=6.2
  - python=3.9
  - pytorch=1.10
  - requests=2.26
  - torchvision=0.10
