name: pytest-gpu-torch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name : Remove CUDA if Mac
      if: startsWith(matrix.os, 'macos')
      run: |
        sed '/cuda/d' environment.yml | tee environment.yml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: torch
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Test pytorch with pytest
      run: |
        pytest src -m "not needs_gpu"